[build]
  publish = "."

[[redirects]]
  from = "/docs/*"
  to = "/docs/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
